
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 6;
  public static final int FROM = 3;
  public static final int AND = 10;
  public static final int COMPARISON = 11;
  public static final int SELECT = 5;
  public static final int RPAREN = 13;
  public static final int SEMI = 2;
  public static final int IN = 8;
  public static final int NOT = 9;
  public static final int PERIOD = 14;
  public static final int NAME = 18;
  public static final int LPAREN = 12;
  public static final int STRING = 17;
  public static final int COMMA = 15;
  public static final int EOF = 0;
  public static final int DISTINCT = 4;
  public static final int error = 1;
  public static final int EXISTS = 7;
  public static final int INTNUM = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "FROM",
  "DISTINCT",
  "SELECT",
  "WHERE",
  "EXISTS",
  "IN",
  "NOT",
  "AND",
  "COMPARISON",
  "LPAREN",
  "RPAREN",
  "PERIOD",
  "COMMA",
  "INTNUM",
  "STRING",
  "NAME"
  };
}

